language: go

go:
 - 1.13.x
 - 1.11.x

os:
 - linux

env:
  global:
   - GOBIN=$HOME/bin
   - PATH=$HOME/bin:$PATH
   - GO111MODULE=on

script:
 - go build -mod=vendor ./...
 - go test -v -race  ./...
